name: custom_marker
description: A package to convert Widget, Local image, Network image, Svg file to BitmapDescriptor which can be used in google_maps_flutter icon marker.
version: 1.1.0
homepage: https://github.com/jmietzITZ/custom_marker

environment:
  sdk: ^3.8.0
  flutter: '3.32.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_cache_manager: ^3.4.1
  google_maps_flutter: ^2.12.3
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
